public enum Action{
    IDLE, 
    MOVE_LEFT, MOVE_RIGHT, 
    MOVEHORIZONTAL_TOWARDS_TARGET, MOVE_TOWARDS_TARGET, MOVE_AWAY_FROM_TARGET, MOVE_BEHIND_TARGET,
    JUMP, FALL_ON_TARGET,
    AIM_TARGET, RELEASE_FIRE_TARGET,
	RUN_SUB_FSM
};

public enum Condition{
    TIMER,
    TARGET_IN_RADIUS, TARGET_OUTSIDE_RADIUS, 
    TARGET_IN_LOS,
    TARGET_IN_OCTANT_BELOW, TARGET_IN_OCTANT_ABOVE,
    TARGET_IN_HORIZONTAL_OCTANTS,
    CLIFF_LEFT, CLIFF_RIGHT
};