public enum ContactState{
	FLATGROUND, AIRBORNE, WALLADJACENT, STEEPSLOPE, BACKGROUNDGRAB
}

public enum MovementDirection{
	UP, DOWN, LEFT, RIGHT, NEUTRAL, NE, NW, SE, SW
}

public enum PhysicMatTypes{
	IDLE_STANDING, FRICTIONLESS, STICKY, LOW_KINETIC_NO_STATIC
}